### ISSUE TITLE
Please elaborate on transactional integrity

### ISSUE THREAD

**Issue by nelisbijl** [mateodelnorte/sourced-repo-mongo#11]
Hi,

First of all my compliments on your simple but elegant implementation of eventsourcing.

I'm a little bit worried about the transactional integrity. As you do know of course, only sinlge inserts in Mongo are atomic. Mongo does not support transactions although they do describe a way to implement 2 phase commits (https://docs.mongodb.com/manual/tutorial/perform-two-phase-commits/)

An alternative that I have seen in another implementation is to store all changes (newEvents plus optionally a new snapshot) in a single record. Thus using Mongo's single insert atomicity.

Then again, what happens if an error occurs when emitting the enqueued events? The commit will return an error, the command will be requeued en re-executed, causing a duplicate insert.

Please eleborate

**Comment by mateodelnorte** [comment]
Thanks, @nelisbijl. Agreed, yes, having a single collection would be a more obvious approach. Both events and snapshots would be saved into that collection in a single insert. I'm not against starting a 1.0.0 branch with that approach, but what I would say is that in practice in multiple businesses including at least one large distributed system with ~8 or so services out of ~30 using one or more sourced models and repos we've not encountered a problem where events were able to be persisted and a snapshot was not. 

For the problem of an error occurring post-commit, causing downstream events to not be published - correct, I chose not to follow a 2 phase commit pattern. In general, these errors can be caught with tests. A good rule is to keep the post-commit logic of your services as thin as possible. This keeps your business logic encapsulated in your message handlers and models and helps keep this problem from occurring. Perhaps it's because services I've helped create and have seen created always have such a thin post-commit publish pattern, but it's not been an issue. 

Something to keep in mind is that your model will be fully consistent so long as your event data is saved, even if the snapshot is not. When developing systems with sourced I always aim to make operations on models idempotent so that in the event that a message is received twice (if for example, a message is retried via servicebus-retry) the end state of the entity is the same, and redundant message publishes (which should result from events emitted from models, post-commit) should not occur. 

All said, if you need 100% obvious rollback-capable transactional integrity, the best thing to do would be to write a sourced-repo-postgres module (my first implementation of event sourcing in node used postgres, but that's tucked away in some proprietary code atm). I can help you knock it out quick, and help make sure it complies to the interface that will allow https://github.com/mateodelnorte/sourced-queued-repo, which I'm finishing up as well. New repo extensions will follow the same interface as well, so both providers should benefit.
